import { readFile, stat } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";
import { DEFAULT_PORT, isValidBridgeToken } from "@browser-research/protocol";

export type ServerConfig = {
  token: string;
  extensionId: string;
  port: number;
  brokerIdleMs: number;
  source: "environment" | string;
};

type ConfigFile = {
  token?: unknown;
  extensionId?: unknown;
  port?: unknown;
  brokerIdleMs?: unknown;
};

export async function loadServerConfig(environment: NodeJS.ProcessEnv = process.env): Promise<ServerConfig> {
  const configPath = environment.BROWSER_RESEARCH_CONFIG ?? defaultConfigPath(environment);
  const needsFile = !environment.BROWSER_RESEARCH_TOKEN || !environment.BROWSER_RESEARCH_EXTENSION_ID;
  const file = needsFile ? await readConfigFile(configPath) : {};
  const token = environment.BROWSER_RESEARCH_TOKEN ?? stringValue(file.token);
  const extensionId = environment.BROWSER_RESEARCH_EXTENSION_ID ?? stringValue(file.extensionId);
  const rawPort = environment.BROWSER_RESEARCH_PORT ?? file.port ?? DEFAULT_PORT;
  const port = typeof rawPort === "number" ? rawPort : Number(rawPort);
  const rawBrokerIdleMs = environment.BROWSER_RESEARCH_BROKER_IDLE_MS ?? file.brokerIdleMs ?? 10 * 60_000;
  const brokerIdleMs = typeof rawBrokerIdleMs === "number" ? rawBrokerIdleMs : Number(rawBrokerIdleMs);

  if (!isValidBridgeToken(token)) {
    throw new Error(`Set BROWSER_RESEARCH_TOKEN or add the 64-character lowercase hexadecimal token generated by setup to ${configPath}`);
  }
  if (!extensionId || !/^[a-p]{32}$/.test(extensionId)) {
    throw new Error(`Set BROWSER_RESEARCH_EXTENSION_ID or add Chrome's 32-character extension ID to ${configPath}`);
  }
  if (!Number.isInteger(port) || port < 1024 || port > 65535) {
    throw new Error("BROWSER_RESEARCH_PORT/config port must be an integer between 1024 and 65535");
  }
  if (!Number.isInteger(brokerIdleMs) || brokerIdleMs < 1_000 || brokerIdleMs > 24 * 60 * 60_000) {
    throw new Error("BROWSER_RESEARCH_BROKER_IDLE_MS/config brokerIdleMs must be between 1000 and 86400000");
  }

  return {
    token,
    extensionId,
    port,
    brokerIdleMs,
    source: environment.BROWSER_RESEARCH_TOKEN && environment.BROWSER_RESEARCH_EXTENSION_ID ? "environment" : configPath
  };
}

export function defaultConfigPath(environment: NodeJS.ProcessEnv = process.env): string {
  const configRoot = environment.XDG_CONFIG_HOME || join(environment.HOME || homedir(), ".config");
  return join(configRoot, "browser-research", "config.json");
}

async function readConfigFile(path: string): Promise<ConfigFile> {
  let contents: string;
  try {
    contents = await readFile(path, "utf8");
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") return {};
    throw new Error(`Could not read browser research config at ${path}: ${errorMessage(error)}`);
  }

  try {
    const parsed: unknown = JSON.parse(contents);
    if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) throw new Error("expected a JSON object");
    await warnIfBroadlyReadable(path);
    return parsed as ConfigFile;
  } catch (error) {
    throw new Error(`Invalid browser research config at ${path}: ${errorMessage(error)}`);
  }
}

async function warnIfBroadlyReadable(path: string): Promise<void> {
  if (process.platform === "win32") return;
  const details = await stat(path);
  if ((details.mode & 0o077) !== 0) {
    process.stderr.write(`Warning: ${path} contains a bridge token and should be readable only by its owner (chmod 600).\n`);
  }
}

function stringValue(value: unknown): string | undefined {
  return typeof value === "string" ? value : undefined;
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
