import { DEFAULT_PORT, isValidBridgeToken } from "@browser-research/protocol";

const form = requireElement<HTMLFormElement>("settings-form");
const tokenInput = requireElement<HTMLInputElement>("token");
const portInput = requireElement<HTMLInputElement>("port");
const status = requireElement<HTMLOutputElement>("status");
const extensionId = requireElement<HTMLElement>("extension-id");
const copyButton = requireElement<HTMLButtonElement>("copy-id");

extensionId.textContent = chrome.runtime.id;

void chrome.storage.local.get(["token", "port", "connectionStatus"]).then((stored) => {
  tokenInput.value = typeof stored.token === "string" ? stored.token : "";
  portInput.value = String(typeof stored.port === "number" ? stored.port : DEFAULT_PORT);
  renderStatus(stored.connectionStatus);
});

form.addEventListener("submit", (event) => {
  event.preventDefault();
  const token = tokenInput.value.trim();
  const port = Number(portInput.value);
  if (!isValidBridgeToken(token) || !Number.isInteger(port) || port < 1024 || port > 65535) {
    status.textContent = "Enter the 64-character lowercase hexadecimal token generated by setup and a valid port.";
    return;
  }
  void chrome.storage.local.set({ token, port }).then(async () => {
    await chrome.runtime.sendMessage({ type: "config_updated" });
    status.textContent = "Saved. Connecting…";
  });
});

copyButton.addEventListener("click", () => {
  void navigator.clipboard.writeText(chrome.runtime.id).then(() => {
    copyButton.textContent = "Copied";
    setTimeout(() => { copyButton.textContent = "Copy ID"; }, 1_500);
  });
});

chrome.storage.onChanged.addListener((changes, areaName) => {
  if (areaName === "local" && changes.connectionStatus) renderStatus(changes.connectionStatus.newValue);
});

function renderStatus(value: unknown): void {
  if (!value || typeof value !== "object") {
    status.textContent = "Not connected";
    return;
  }
  const record = value as Record<string, unknown>;
  status.textContent = record.connected
    ? `Connected${typeof record.message === "string" ? ` — ${record.message}` : ""}`
    : `Disconnected${typeof record.message === "string" ? ` — ${record.message}` : ""}`;
}

function requireElement<T extends HTMLElement>(id: string): T {
  const element = document.getElementById(id);
  if (!element) throw new Error(`Missing element #${id}`);
  return element as T;
}
